### PR TITLE
Add gitignore

### PR DESCRIPTION
**Pull request by G07cha**
Common practice to prevent occasional committing of build/make files.

### CODE REVIEW

**Comment by gafferongames** [comment]
Looks good. I'll extend it to cover the common Visual C++ types as well.

**Comment by gafferongames** [comment]
OK this is a nice safety. I usually go:

    premake5 clean
    git add *
    git commit -am "whatever"
    git push

But I just tested this catches it when I forget the clean step. Thanks!

**Comment by gafferongames** [comment]
Alright. It's extended now to cover all the file patterns matched in "premake5 clean" step, as well as all directories that should never be committed.

Thanks for speeding up my commit process. Appreciated.

**Comment by G07cha** [comment]
@gafferongames oh, I'm actually missed a lot of stuff, thanks for checking and improvement.

**Pull request merged**
