### PR TITLE
Revert "Set both ipv4 and ipv6 to 0 in Address::Clear()"

### PR DESCRIPTION
**Pull request by gafferongames**
Reverts networkprotocol/libyojimbo#11

### CODE REVIEW

**Comment by gafferongames** [comment]
For future reference, was reverted because Address stores IPv4 and IPv6 data in a union, so clearing both ipv4 and ipv6 data to zero in Address::Clear is not necessary. Clearing ipv6 is sufficient, since it is larger.

**Comment by kkimdev** [comment]
Maybe it's worth documenting in the code?

**Comment by gafferongames** [comment]
Possibly. I'll see if I can structure the code in some nicer way that I can name the union, and then memset the whole union to 0 instead. This "feels" better.

**Comment by RandyGaul** [comment]
Would this be OK:

	union
	{
		uint32_t ipv4;
		uint16_t ipv6[ 8 ];
	} u;
	
	memset( u, sizeof( u ) );

**Comment by gafferongames** [comment]
Yeah that looks good. So accesses to the ipv4 and ipv6 become u.ipv4, u.ipv6 throughout the class then?

**Comment by gafferongames** [comment]
I like this because it makes it easier to add new address types in the future, (eg. steam id, NPid, whatever for specific platforms), and there is no longer a loaded shotgun pointing at your feet, if you just happen to add a new address type that is larger than ipv6.

**Comment by RandyGaul** [comment]
Yep! Exactly. This is an old C trick I read in a book a long while back. Good for exactly reasons you explained.

**Comment by gafferongames** [comment]
I've coded this, but called the union address. Therefore the code change is simply: m_address_ipv4 -> m_address.ipv4, and so on. I'll push to mainline shortly with a bunch of documentation I've been working on lately.

**Pull request merged**
